name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4
      - name: "PHP Composer install"
        run:  composer install --ignore-platform-reqs
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          password: "${{ secrets.SSH_PASS }}"
          source: "."
          target: "/home/projetos/pdf-search"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd /home/projetos/pdf-search
            docker compose up -d